DELETE http://localhost:8080/events/1/delete
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzQ5NTMxMzQ4LCJ1c2VySWQiOjJ9.gb7EbiIjrdf52l4ejRQKDhLZasd013JAr7gIf8LkMi4
